name: first work flow
on: push
jobs:
    my_first_job: 
     runs-on: ubuntu-latest
     steps:
        - name: hello message 
          run: echo "hello world"
        - name: list files
          run: |
            ls  
        - name: checkout action
          uses: actions/checkout@v4      
        - name: open the file
          run: cat README.md    
            

    